# Generated by Django 6.0.3 on 2026-03-04 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adotante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('endereco', models.TextField()),
                ('doc_identificacao', models.ImageField(upload_to='documento/')),
            ],
        ),
        migrations.CreateModel(
            name='FotoMoradia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='fotos_moradia/')),
                ('adotante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='gestao_adocao.adotante')),
            ],
        ),
    ]
