# Generated by Django 6.0.3 on 2026-03-20 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adotante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=20, unique=True)),
                ('endereco', models.TextField()),
                ('cep', models.CharField(max_length=9)),
                ('renda_familiar', models.CharField(choices=[('ate_2000', 'R$1.000 a R$2.000'), ('ate_3000', 'R$2.000 a R$3.000'), ('acima_3000', 'Acima de R$3.000')], max_length=20)),
                ('pessoas_na_familia', models.CharField(choices=[('1', '1 pessoa'), ('2', '2 pessoas'), ('3', '3 pessoas'), ('4', '4 pessoas'), ('5', '5 pessoas'), ('acima_5', 'Acima de 5 pessoas')], max_length=10)),
                ('tipo_moradia', models.CharField(choices=[('casa', 'Casa'), ('apartamento', 'Apartamento'), ('chacara', 'Chácara')], max_length=20)),
                ('possui_outros_pets', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3)),
                ('experiencia_pets', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3)),
                ('motivo_adocao', models.TextField()),
                ('doc_identificacao', models.ImageField(upload_to='documento/')),
                ('criado_em', models.DateField(auto_now_add=True)),
                ('atualizado_em', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('em_analise', 'Aguardando Análise'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='em_analise', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FotoMoradia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='fotos_moradia/')),
                ('adotante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='gestao_adocao.adotante')),
            ],
        ),
    ]
