# Generated by Django 6.0.3 on 2026-03-23 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_adocao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adotante',
            name='doc_identificacao',
        ),
        migrations.CreateModel(
            name='DocumentoIdentificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_identificacao', models.ImageField(upload_to='documento/')),
                ('adotante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='gestao_adocao.adotante')),
            ],
        ),
    ]
