# Generated by Django 6.0.4 on 2026-04-29 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_adocao', '0002_remove_adotante_doc_identificacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_doacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Doação',
                'verbose_name_plural': 'Doações',
            },
        ),
    ]
