# Generated by Django 6.0.3 on 2026-03-18 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_adocao', '0002_alter_adotante_experiencia_caes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adotante',
            name='status',
            field=models.CharField(choices=[('em_analise', 'Aguardando Análise'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='em_analise', max_length=20),
        ),
    ]
